### ISSUE TITLE
unable to open file:///tmp/......../*.pdf

### ISSUE THREAD

**Issue by noirkarso** [xuhdev/vim-latex-live-preview#31] opened 2017-07-11 15:48 UTC
If the system is freshly rebooted, everything worked just fine for the first time the .tex file is opened. After that the unable to open pdf error comes out. 
I am with archlinux. What should I do to make it work anytime I want.

**Comment by badouralix** [comment] 2017-07-12 13:04
What do you mean by *for the first time*? Like, open the tex file in vim once, run `:LLPStartPreview`, close the file, re-open it and re-run `:LLPStartPreview`?
Could you provide the output of `:echo b:livepreview_buf_data` after running `:LLPStartPreview` in both cases?

**Comment by noirkarso** [comment] 2017-07-12 22:00
I am using evince as document viewer. After system rebooting, the :LLPStartPreview can call out the viewer and the live preview works fine. After that, the other file editing still can call out the viewer, but the viewer gives the error massage " unable to open file:///......." unless the system is freshly reboot again. 
My guess is something wrong with the evince. But how can I fix it?

**Comment by badouralix** [comment] 2017-07-12 23:57
I'm also using evince on archlinux, but as I cannot reproduce this bug, I don't really know how it could be fixed. Could you provide an actual example as use case where the error message occurs, along with the version number of vim, evince, etc. and any other uncommon system configuration?
Could you provide the output of `:echo b:livepreview_buf_data` after running `:LLPStartPreview` in a case of success and in a case of failure?

**Comment by noirkarso** [comment] 2017-07-13 04:15
evince gives the error massage. livepreview_buf_data gave regular successful running info. I don't understand why the evince can not open the pdf file from the file:///........ The pdf file is in the folder and can be opened by evince directly. It just can not be opened via the vim by LLPStartPreview command.

**Comment by badouralix** [comment] 2017-07-13 12:09
Can it be opened by evince using a shell command inside vim, like `:!evince /tmp/vim-latex-live-preview-XXXXXX/path/to/file`?

**Comment by noirkarso** [comment] 2017-07-13 12:39
I found the reason. Somehow, it only works with xelatex. So it works properly after being replaced all pdflatex with xelatex in latexlivepreview.vim.

**Comment by badouralix** [comment] 2017-07-13 12:47
Honestly, I find this bug really strange... Specially because compilation succeed and only viewing failed. Could you provide such an example of tex project where the bug occurs, to look for a possible fix?

Also, the pdf engine can be overridden without patching the plugin. Add this line in your `vimrc` file:
```vim
let g:livepreview_engine = 'xelatex'
```

**Comment by badouralix** [comment] 2017-07-15 17:28
I'm closing this issue, but feel free to add some info to allow further investigation.

**Closed** 2017-07-15 17:28 UTC

**Comment by willbelr** [comment] 2020-02-06 13:11
I experienced the same bug on Arch, and replacing the engine did not fix it. It turned out the pdf was not generated because the document was empty.

So this works:
```
\documentclass{article}
\begin{document}
\begin{abstract}
The abstract text goes here.
\end{abstract}
\end{document}
```

And this does not:
```
\documentclass{article}
\begin{document}

\end{document}
```

**Comment by sasi1970** [comment] 2021-08-19 15:03
> Honestly, I find this bug really strange... Specially because compilation succeed and only viewing failed, and only in vim, not by opening the file with evince directly. Could you provide such an example of tex project where the bug occurs, to look for a possible fix?
> 
> Also, the pdf engine can be overridden without patching the plugin. Add this line in your `vimrc` file:
> 
> ```viml
> let g:livepreview_engine = 'xelatex'
> ```

This worked for me too, thanks a lot!
